### ISSUE TITLE
Add wasm-bindgen-macro

### ISSUE THREAD

**Issue by colelawrence** [jakobhellermann/watt-contrib#1]
Would it be feasible to add https://github.com/rustwasm/wasm-bindgen/tree/master/crates/macro to the repo here?

**Comment by jakobhellermann** [comment]
has been added in https://github.com/jakobhellermann/watt-contrib/commit/a34cfac355ab5061a1790dd1a16ef401003db005 :)

`cargo watt build --crate wasm-bindgen-macro`
